#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache'
mod 'puppetlabs-apt'
mod 'puppetlabs-mysql', "3.2.0"

mod 'thias-php', "1.1.1"

mod 'thbe-ssmtp'
mod 'ftaeger-mailhog'

mod 'willdurand-composer'

mod 'jlondon-wkhtmltox'

mod 'clwdev-precip', :path => '/vagrant/puppet/precip'