#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache'
mod 'puppetlabs-apt', "4.1.0"
mod 'puppetlabs-mysql'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-stdlib'
mod 'ftaeger-mailhog', "1.1.0"

mod 'puppet-php',
  :git => "https://github.com/voxpupuli/puppet-php.git"

mod 'saz-memcached'

mod 'clwdev-precip', :path => '/vagrant/puppet/precip'