#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache'
mod 'puppetlabs-apt'
mod 'puppetlabs-mysql', "3.2.0"

mod 'thias-php'

mod 'actionjack-mailcatcher'

mod 'willdurand-composer'

mod 'jeffgeorge-precip', :path => '/vagrant/puppet/precip'